example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_mywatchlist_xml
from mywatchlist.views import show_mywatchlist_json

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_mywatchlist_xml, name='show_mywatchlist_xml'),
    path('json/', show_mywatchlist_json, name='show_mywatchlist_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from asyncio import create_task
from unicodedata import name
from django.urls import path
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import change_status
from todolist.views import delete_task
from todolist.views import show_todolist_ajax
from todolist.views import show_json
from todolist.views import add_task

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist_ajax, name='show_todolist_ajax'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('change-status/<int:id>', change_status, name='change_status'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('json/', show_json, name='show_json'),
    path('add/', add_task, name='add_task'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=250)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class TaskForm(forms.Form):
    task_title = forms.CharField(label="Title")
    task_description = forms.CharField(label="Description", widget=forms.Textarea)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_katalog': data_barang_katalog,
        'nama': 'Devina Hana',
        'id': '2106751032',
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from email import message
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    data = MyWatchList.objects.all()
    data_sudah_ditonton = MyWatchList.objects.filter(watched=True).count()
    data_belum_ditonton = MyWatchList.objects.filter(watched=False).count()
    if (data_sudah_ditonton >= data_belum_ditonton):
        message = "Selamat, kamu sudah banyak menonton!"
    else:
        message = "Wah, kamu masih sedikit menonton!"

    context = {
        'movie_list': data,
        'nama': 'Devina Hana',
        'id': 2106751032,
        'message': message
    }
    return render(request, "mywatchlist.html", context)

def show_mywatchlist_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_mywatchlist_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from turtle import title
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from todolist.models import Task
from todolist.forms import TaskForm
from datetime import date
from django.http import HttpResponse
from django.core import serializers
from django.http import HttpResponseRedirect
from django.urls import reverse

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    data = Task.objects.filter(user=request.user).all()
    context = {
        'todo_list': data,
    } 
    return render(request, "todolist.html", context)

def show_json(request):
    data = Task.objects.filter(user=request.user).all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        new_task = Task(
            date=str(date.today()),
            title=title, 
            description=description,
            user=request.user,
        )
        new_task.save()
        return HttpResponse(
            ''
        )
    return redirect('todolist:show_todolist_ajax')
    

def create_task(request):
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = Task(
                date = str(date.today()),
                title = form.cleaned_data["task_title"],
                description = form.cleaned_data["task_description"],
                user = request.user,
            )
            task.save()
            messages.success(request, 'Task berhasil dibentuk')
            return redirect('todolist:show_todolist')
    context = {"form": form}
    return render(request, 'create_task.html', context)

def delete_task(request, id):
    Task.objects.get(pk=id).delete()
    return redirect('todolist:show_todolist_ajax')

def change_status(request, id):
    task = Task.objects.get(pk=id) 
    if (not task.is_finished):
        task.is_finished = True
    task.save()
    return redirect('todolist:show_todolist_ajax')

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save() 
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist_ajax')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    messages.info(request, 'Berhasil logout')
    return redirect('todolist:login')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>

  <table>
    
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    
    {% for barang in list_katalog %}
      <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

  {% block content %}

  <h1>My Watchlist</h1>
  <h3>{{message}}</h3>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>


  <table>
    
    <tr>
      <th>Title</th>
      <th>Watched</th>
      <th>Release Date</th>
      <th>Rating</th>
      <th>Review</th>
    </tr>

    {% for movie in movie_list %}
      <tr>
        <th>{{movie.title}}</th>
        <th>{{movie.watched}}</th>
        <th>{{movie.release_date}}</th>
        <th>{{movie.rating}}</th>
        <th>{{movie.review}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create New Task</title>
{% endblock meta %}

{% block content %}

<style>
    input, textarea {
        padding: 0.5rem;
        border: 1px solid;
        border-radius: 8px;
        width: 100%
    }
</style>

<div class="position-relative mx-auto container flex flex-col gap-4 pt-8" style="margin-top: 15px; text-align: center">
    <div class ="rounded-lg p-4 flex flex-col gap-4 mx-auto bg-base-100;" >
    
        <h1 style="padding-bottom: 10px; font-size: 40px;" class="font-monospace fw-semibold text-center">New Task</h1>
    
        <form method="POST" action="" style="display: inline-block;">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td colspan="2"><input style="width: 100%; margin-top: 20px; margin-bottom: 7px;" class="btn btn btn-dark" type="submit" name="submit" value="Create"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
    </div>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="position-relative" style="margin-top: 150px; text-align: center;">

    <div class ="login position-absolute top-50 start-50 translate-middle" >
    
        <h1 style="padding-top: 150px; padding-bottom: 10px; font-size: 40px;" class="font-monospace fw-semibold text-center">Login</h1>

    
        <form method="POST" action="">
            {% csrf_token %}
            <table style="width: 100%;">
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                    <td colspan="2"><input style="width: 100%; margin-top: 20px; margin-bottom: 7px;" class="btn login_btn btn btn-dark" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
    
    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<style>
    *{ 
    margin: 0; 
    padding: 0; 
    box-sizing: border-box; 
} 
 
 
.container{ 
    width: 90%; 
    margin: auto; 
} 
 
.input-group{ 
    position: relative; 
    margin-bottom: 5px; 
} 
 
.form-input{ 
    padding: 10px; 
    width: 100%; 
    border-radius: 10px; 
    text-indent: 0%; 
} 
 

</style>

<div class = "login container">
    
    <h1 class="font-monospace fw-semibold text-center" style="margin-top: 20px;">Formulir Registrasi</h1>  

        <div style="padding-top: 15px;">
            
            <form method="POST" >  
                {% csrf_token %}  
                <div class="input-group"> 
                    <input required name="username" id="username" type="text" class="form-input" placeholder="username" maxlength="16" minlength="6"> 
                </div>
                <div class="input-group"> 
                    <input required name="password1" id="password1" type="password" class="form-input" placeholder="password" maxlength="22" minlength="8"> 
                </div> 
                <div class="input-group"> 
                    <input required name="password2" id="password2" type="password" class="form-input" placeholder="password confirmation" maxlength="22" minlength="8"> 
                </div> 
                <input type="submit" style="margin-top: 15px; width: 100%;" class="btn btn-dark" name="submit" value="Daftar"/>
            </form>
        </div>


    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

  {% block content %}

  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        function posting(e) {
          e.preventDefault()
          const title = $("#title").val()
          const description = $("#description").val()
          
          const data = {
            title: title,
            description: description,
            csrfmiddlewaretoken: "{{ csrf_token }}"
          }
          
          $.ajax({
            type: 'POST',
            url: '{% url "todolist:add_task" %}',
            data: data,
            success: function() {
              $.get("/todolist/json", update)
            },
          });

        }
      
        function update(data) {
          const myElement = $("#main-div")
          myElement.html('');
          for (let i = 0; i < data.length; i++) {
            let message = (data[i].fields.is_finished) ? 'Done':'Not Done';
            let color = (data[i].fields.is_finished) ? 'green':'red';
            myElement.append(`
              <div class="card col-sm-4 mb-1 mt-4 mx-auto" style="width: 18rem;">
                <div class="card-body">
                  <h4 class="card-title text-center fw-semibold">${data[i].fields.title}</h4>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item text-secondary">${data[i].fields.date}</li>
                    <li class="list-group-item">${data[i].fields.description}</li>
                  </ul>
                </div>
                <div class="card-footer text-center">
                  <p style="font-weight:bold; color:${color};">${message}</p>
                  <button type="button" class="btn btn-dark" style="float:left;"><a class="text-light" href="change-status/${data[i].pk}" style="text-decoration:solid ">Finish Task</a></button>
                  <button type="button" class="btn btn-dark" style="float:right;"><a class="text-light" href=" delete-task/${data[i].pk}" style="text-decoration:solid ">Delete Task</a></button>
                </div>
              </div>
            `)
          }
        }
      
        function fetchData() {
          $.get("/todolist/json", update)
        }
      
        $(document).ready(() => {
          $("#create-button").click(posting)
          fetchData()
        })
    </script>
    <style>
        
      .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        width: 40%;    
        border-radius: 5px;
        background-color: rgb(254, 224, 229);
      }
          
      .card:hover {
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06); 
        background-color: rgb(7, 5, 5); 
        color: white;  
      }
      
      .container {
        padding: 2px 16px;
      }
        
      .content {
        padding-left: 15px;
        padding-right: 15px;
      }
          
      @keyframes gradient {
        0% {
          background-position: 0% 50%;
        }
        50% {
          background-position: 100% 50%;
        }
        100% {
          background-position: 0% 50%;
        }
      }

      input, textarea {
        padding: 0.5rem;
        border: 1px solid;
        border-radius: 8px;
        width: 100%
      }
          
    </style>
  </head>



  <h1 style="margin-top:7px; padding-top: 70px; padding-bottom:15px ;font-size: 40px;" class="font-monospace fw-semibold text-center">To Do List</h1>

  <header>
    <nav class="navbar navbar-expand-lg bg-light bg-gradient fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#main-table">Hi, {{user.username}}!</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item" style="margin: 5px;">
              <a class="btn btn-dark" data-bs-toggle="modal" href="#addTask" role="button">Add Task</a>
            </li>
            <li class="nav-item" style="margin: 5px;">
              <a class="btn btn-dark" href="{% url 'todolist:logout' %}" role="button">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  
  <div class="row row-cols-1 row-cols-md-3 g-4 md:justify-end gap-4" id="main-div"></div>
  
  <div class="modal fade" id="addTask" tabindex="-1" aria-labelledby="addTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Task</h1>
        </div>
        <div class="modal-body">
          <form method="POST" action="" style="display: inline-block;">
            {% csrf_token %}
            <table>
                <tr>
                  <label>Title</label>
                  <input type="text" name="title" id="title">
                </tr>
                <tr>
                  <label>Description</label>
                  <input type="textarea" name="description" id="description">
                </tr>
                    <td colspan="2">
                      <input data-bs-dismiss="modal" style="width: 100%; margin-top: 20px; margin-bottom: 7px;" class="btn btn btn-dark" type="submit" name="submit" value="Create" id="create-button">
                    </td>
                </tr>
            </table>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


 {% endblock content %}